version: '3.4'

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dbGuardian@2020
      MYSQL_DATABASE: backend
    volumes:
      - ./database/backup:/home/backup
      - ./database/init:/docker-entrypoint-initdb.d
      - mariadb-portfolio:/var/lib/mysql
    ports: 
      - "3306:3306"

  backend:
    image: portfolio-backend
    build:
      context: .
      dockerfile: ./Dockerfile-backend
      target: prod
    environment:
      DB_ENGINE: mysql
      DB_NAME: backend
      DB_USER: root
      DB_PASSWORD: dbGuardian@2020
      DB_HOST: database
      DB_PORT: 3306
    volumes:
      - ./vs_ext:/home/vs_ext
      - ./backend:/home/backup
    depends_on: 
      - database

  frontend:
    image: portfolio-frontend
    build:
      context: .
      dockerfile: ./Dockerfile-frontend
      target: prod
    volumes:
      - ./vs_ext:/home/vs_ext
      - ./frontend:/home/backup
    ports: 
      - '3000:3000'


volumes: 
  mariadb-portfolio: