"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from library.config import getDBConfig
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ei(p_8bde)b#t@u5s+)f5+x+o97ek)!8ba%)+4!05f5d3p1!)t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ['DJANGO_ENV'] == 'dev' else False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'apps.contacts',
    'rest_framework',
]

MIDDLEWARE = [
    'library.middleware.disableCSRF', #Disable CSRF completely since use auth token tweak
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

WSGI_APPLICATION = 'website.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = getDBConfig(BASE_DIR, TIME_ZONE)


# Rearrange password hashing algorithm to prioritize bcrypt
# https://docs.djangoproject.com/en/3.1/topics/auth/passwords/#using-bcrypt-with-django

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# Session engine settings
# https://docs.djangoproject.com/en/3.1/ref/settings/#sessions

SESSION_COOKIE_NAME = 'signature'

SESSION_ENGINE = 'library.jwtsession.backend'

SESSION_SAVE_EVERY_REQUEST = True


# File management setting, set temporary upload file directory
# https://docs.djangoproject.com/en/3.1/ref/settings/#file-upload-temp-dir

FILE_UPLOAD_TEMP_DIR = BASE_DIR / 'tmp'


# Static files
# https://docs.djangoproject.com/en/3.1/ref/settings/#static-files

STATIC_URL = '/files/'

STATIC_ROOT = BASE_DIR / 'files'


# REST Framework settings

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'library.pagination.PageSizedPagination',
    'PAGE_SIZE': 100
}